### ISSUE TITLE
paladin issue while running macrel abundance

### ISSUE THREAD

**Issue by earthspirit123** [BigDataBiology/macrel#60]
Hello im currently trying to run 

macrel abundance -1 may10.fq.gz --fasta macrelabundancepeptides.faa  --output out_abundancemay15latest --force

However I am receiving this error

```
[main] Version: 1.3.1
[main] CMD: paladin index -r3 /tmp/tmpdrzjismz/paladin.faa
[main] Real time: 0.051 sec; CPU: 0.009 sec
align: invalid option -- 'z'
Output folder already exists, but --force flag was usedTraceback (most recent call last):
  File "/home/user/.conda/envs/macrelabundancemay15/bin/macrel", line 10, in <module>
    sys.exit(main())
  File "/home/user/.conda/envs/macrelabundancemay15/lib/python3.9/site-packages/macrel/main.py", line 340, in main
    do_abundance(args, tdir,logfile)
  File "/home/user/.conda/envs/macrelabundancemay15/lib/python3.9/site-packages/macrel/main.py", line 195, in do_abundance
    subprocess.check_call([
  File "/home/user/.conda/envs/macrelabundancemay15/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['paladin', 'align', '-t', '1', '-T', '20', '-f', '10', '-z', '11', '-a', '-V', '-M', '/tmp/tmpdrzjismz/paladin.faa', '/tmp/tmpdrzjismz/preproc.fq.gz']' returned non-zero exit status 1.
```
the reads file is 14gb. 

Looking forward for your help and feedback

**Comment by celiosantosjr** [comment]
Dear earthspirit123,

Before we start the debugging, which version of Macrel are you using?

We need you to confirm that the fastq structure and peptides file structure
are preserved, if there is any corrupted file that may be the cause, you
can do:

for gzipped files:

```
gzip -v -t file.gz
```

for uncompressed files:

```
if cat somefile > /dev/null 2>&1 ; then
         echo file is ok
    else
         echo file is corrupt
fi
```
You can also check the fastq and fasta structures by doing as recommended
in stackoverflow forum:

https://stackoverflow.com/questions/69603686/how-can-i-check-if-a-file-is-a-real-fastq-python

The size of the files should not matter. Your error seems to be related to
installing, do you opt for conda or github repository?

Best regards,
Celio

**Comment by earthspirit123** [comment]
Apologies for the delayed response as I tried to reinstall macrel and checked if my files were corrupted

I am grateful for your advice, I was able to run the abundance command with a new macrel installation and I have updated the integrity of my files to fit the fasta format.

Wishing you all the best
