### ISSUE TITLE
ModuleNotFoundError: No module named '_sysconfigdata_x86_64_conda_linux_gnu'

### ISSUE THREAD

**Issue by ofleitas** [BigDataBiology/macrel#71]
Hello 

I am trying to run macrel but I got the follow error:

# Sequence Data: seqnum=7183;seqlen=1609;seqhdr="k127_22397 flag=3 multi=7.0047 len=1609"
# Model Data: version=Prodigal.v2.6.3;run_type=Metagenomic;model="11|Candidatus_Amoebophilus_asiaticus_5a2|B|35.0|11|0";gc_cont=35.00;transl_table=11;uses_sd=0
>1_302_409_-
Traceback (most recent call last):
  File "/home/ofm/anaconda3/envs/env_macrel/bin/macrel", line 11, in <module>
    sys.exit(main())
  File "/home/ofm/anaconda3/envs/env_macrel/lib/python3.7/site-packages/macrel/main.py", line 282, in main
    do_predict(args, tdir)
  File "/home/ofm/anaconda3/envs/env_macrel/lib/python3.7/site-packages/macrel/main.py", line 241, in do_predict
    fs)
  File "/home/ofm/anaconda3/envs/env_macrel/lib/python3.7/site-packages/macrel/AMP_predict.py", line 7, in predict
    model1 = pickle.load(gzip.open(model1, 'rb'))
  File "/home/ofm/anaconda3/envs/env_macrel/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/ofm/anaconda3/envs/env_macrel/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/ofm/anaconda3/envs/env_macrel/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 25, in <module>
    from . import _joblib
  File "/home/ofm/anaconda3/envs/env_macrel/lib/python3.7/site-packages/sklearn/utils/_joblib.py", line 7, in <module>
    import joblib
  File "/home/ofm/anaconda3/envs/env_macrel/lib/python3.7/site-packages/joblib/__init__.py", line 113, in <module>
    from .memory import Memory, MemorizedResult, register_store_backend
  File "/home/ofm/anaconda3/envs/env_macrel/lib/python3.7/site-packages/joblib/memory.py", line 16, in <module>
    import pydoc
  File "/home/ofm/anaconda3/envs/env_macrel/lib/python3.7/pydoc.py", line 370, in <module>
    class Doc:
  File "/home/ofm/anaconda3/envs/env_macrel/lib/python3.7/pydoc.py", line 402, in Doc
    def getdocloc(self, object, basedir=sysconfig.get_path('stdlib')):
  File "/home/ofm/anaconda3/envs/env_macrel/lib/python3.7/sysconfig.py", line 521, in get_path
    return get_paths(scheme, vars, expand)[name]
  File "/home/ofm/anaconda3/envs/env_macrel/lib/python3.7/sysconfig.py", line 511, in get_paths
    return _expand_vars(scheme, vars)
  File "/home/ofm/anaconda3/envs/env_macrel/lib/python3.7/sysconfig.py", line 172, in _expand_vars
    _extend_dict(vars, get_config_vars())
  File "/home/ofm/anaconda3/envs/env_macrel/lib/python3.7/sysconfig.py", line 559, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/home/ofm/anaconda3/envs/env_macrel/lib/python3.7/sysconfig.py", line 430, in _init_posix
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
ModuleNotFoundError: No module named '_sysconfigdata_x86_64_conda_linux_gnu' 

What can I do?

Thanks in advance

**Comment by ofleitas** [comment]
Hello again

I think that I solved the problem but now I am getting the following error:

# Sequence Data: seqnum=7183;seqlen=1258;seqhdr="k127_3767 flag=1 multi=3.0000 len=1258"
# Model Data: version=Prodigal.v2.6.3;run_type=Metagenomic;model="48|Xylella_fastidiosa_Temecula1|B|51.8|11|1";gc_cont=51.80;transl_table=11;uses_sd=1
>1_83_418_+
>2_749_1246_-
/home/ofm/anaconda3/envs/env_macrel/lib/python3.7/site-packages/sklearn/base.py:338: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.22.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  UserWarning,
/home/ofm/anaconda3/envs/env_macrel/lib/python3.7/site-packages/sklearn/base.py:338: UserWarning: Trying to unpickle estimator RandomForestClassifier from version 0.22.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  UserWarning,
/home/ofm/anaconda3/envs/env_macrel/lib/python3.7/site-packages/sklearn/base.py:444: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
/home/ofm/anaconda3/envs/env_macrel/lib/python3.7/site-packages/sklearn/base.py:444: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
/home/ofm/anaconda3/envs/env_macrel/lib/python3.7/site-packages/sklearn/base.py:444: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
/home/ofm/anaconda3/envs/env_macrel/lib/python3.7/site-packages/sklearn/base.py:444: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"

What can I do?
Thank you in advance

**Comment by luispedro** [comment]
The previous error was some conda issue. These are hard to debug, glad you figured it out.

The warnings that you are getting now can be safely ignored (although we should still fix the code to get rid of them)

**Comment by ofleitas** [comment]
Ok. Thank you very much.
When I get the warnings the prediction output file is empty it only contains the column headers. Does this mean that no AMPs were found?

**Comment by luispedro** [comment]
Yes, none were found

**Comment by ofleitas** [comment]
OK. Thank you very much

**Comment by WW-web-ctrl** [comment]
May I ask how you solved the first conda problem
Thank you in advance

**Comment by ofleitas** [comment]
Hello

If my memory serves me correctly, it was by following these instructions :

https://stackoverflow.com/questions/68261254/conda-error-sysconfigdata-x86-64-conda-linux-gnu

hope it help
